// This file is generated by BpValueBox.Build.cs. It will be overwritten during build configuration.
// Add nothing here by hand; if you need to customize generation, modify BpValueBox.Build.cs.

#pragma once

// Generated boxed types will be written here.
